services:
  backend:
    build: ./backend-java
    container_name: splitzilla-backend
    network_mode: host
    environment:
      SERVER_PORT: 8001
      SPRING_DATA_MONGODB_URI: mongodb+srv://karans0811_db_user:XAEmhXQiPJhhDyCD@cluster0.54x4icu.mongodb.net/splitzilla?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build: ./frontend
    container_name: splitzilla-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
