services:
  backend:
    build: ./backend-java
    container_name: splitzilla-backend
    ports:
      - "8001:8000"

  frontend:
    build: ./frontend
    container_name: splitzilla-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
